---
#Mediante este playbook se instalar치n dependencias, chrony y su configuraci칩n para CentOS y Ubuntu
  - name: Instalaci칩n de paquetes
    hosts: all
    gather_facts: yes
    become: yes
    tasks:
      - name:
        include_vars:
          file: "{{ ansible_facts.distribution }}.yml"
    
      - name: Instalar chrony en cada servidor
        package:
          name: chrony
          state: present

      - name: Instala dependencias en cada servidor
        package:
          name: "{{ packages }}"
          state: present

      - name: Configuraci칩n de archivo de chrony
        template: 
          src: chrony.conf.j2
          dest: /etc/chrony.conf
        notify: restart chrony

      - name: Start the chrony service
        service: 
              name: "{{ tiempo }}"
              state: started
              enabled: true
    handlers:
      - name: restart chrony
        service: 
          name: "{{ tiempo }}"
          state: restarted
          